/**
 * Build script
 *
 * Usage:
 *
 * Override output dir via env:
 *   RTT_OUT_DIR=/path/to/plugin bun build.ts
 *
 * This script is type-checked separately; tsconfig excludes it on purpose.
 */

import { mkdir, watch } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';

const ROOT = import.meta.dir;

/**
 * The vault plugin directory (deploy target), supplied by the caller.
 *
 * Deliberately not hardcoded: a local vault path must never be committed. Set it when
 * deploying, e.g.
 *
 *   RTT_VAULT_PLUGIN_DIR=/path/to/vault/.obsidian/plugins/documents-activity-tracker \
 *     bun build.ts --deploy
 */
const VAULT_PLUGIN_DIR = process.env.RTT_VAULT_PLUGIN_DIR ?? '';

/**
 * The bundled sql.js wasm.
 *
 * SQLite adds one binary artifact beside main.js: the wasm can neither be inlined (a
 * ~1MB base64 blob) nor fetched (CSP and mobile path differences), so it ships next to
 * main.js and is read through the vault adapter at runtime.
 */
const SQL_WASM_SOURCE = path.join(ROOT, 'node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');
const SQL_WASM_NAME = 'sql-wasm.wasm';

const OUT_DIR = process.env.RTT_OUT_DIR ?? path.join(ROOT, 'dist');

const PROD = process.argv.includes('--prod') || process.argv.includes('--deploy');
const DEPLOY = process.argv.includes('--deploy');
const WATCH = process.argv.includes('--watch');

const BANNER = '/* Documents Activity Tracker — generated by bun build. DO NOT EDIT. */';

/**
 * CSS concatenation order — MUST NOT be reordered.
 *
 * Blocks from `60-widget-mobile` onward override the desktop base styles in
 * `10-widget`. Specificity is identical, so document order decides; a wrong
 * order makes the mobile layout fall back to desktop styling.
 */
const CSS_MODULES_BASE = [
  '00-header.css',
  '10-widget.css',
  '20-modal.css',
  '30-records-list.css',
  '40-timeline-view.css',
  '50-heatmap.css',
  '60-widget-mobile.css',
  '70-mobile-controls.css',
  '80-widget-collapse.css',
  '85-mobile-toggle.css',
  '90-session-detail.css',
  '92-state-sequence.css',
  '94-state-chain.css',
] as const;

/**
 * New style modules outside the gate.
 *
 * New UI (such as the sidebar) may add style modules here; they are appended after the
 * gated ones. The gate covers only `CSS_MODULES_BASE`, so adding modules cannot fail it,
 * while the guarantee that the original 13 modules are untouched still holds.
 */
const CSS_MODULES_EXTRA: readonly string[] = [
  // panel tabs and the records browser toolbar
  '95-sidebar.css',
];

/** final order: gated base, then extras. */
const CSS_MODULES: readonly string[] = [...CSS_MODULES_BASE, ...CSS_MODULES_EXTRA];

/**
 * Style regression gate.
 *
 * md5 of the concatenation of `CSS_MODULES_BASE`, so any edit to one of those 13 modules
 * fails the build until the value is updated deliberately.
 *
 * It used to hold the md5 of the pre-split monolithic styles.css, proving the split had
 * been byte-faithful. That proof is spent: `90-session-detail.css` carried an orphaned
 * declaration block and a stray `}` (a CSS parser drops both, so nothing rendered
 * differently, but a linter rejects the file). Removing them was deliberate, so the
 * reference now simply records the concatenation as of that fix.
 */
const CSS_REFERENCE_MD5 = 'e7530c7666b9b8899604bc76651d0a49';

const md5 = (data: Uint8Array | string): string =>
  createHash('md5').update(data).digest('hex');

/** Build the JS bundle. */
async function buildJs(): Promise<void> {
  const result = await Bun.build({
    entrypoints: [path.join(ROOT, 'src/main.ts')],

    //  Note: the Bun.build JS API has no `outfile` (that's a CLI flag). Use outdir + naming.
    outdir: OUT_DIR,
    naming: 'main.js',
    format: 'cjs', // Loader requires CommonJS
    target: 'browser', // Renderer process, not node
    external: ['obsidian'], // Injected by the host, never bundled
    bundle: true,
    splitting: false,
    minify: PROD,
    sourcemap: PROD ? 'none' : 'inline',
    banner: BANNER,
    define: {
      'process.env.NODE_ENV': JSON.stringify(PROD ? 'production' : 'development'),
    },
  });

  if (!result.success) {
    for (const log of result.logs) console.error('[build] ', log);
    throw new Error('JS 构建失败 / JS build failed');
  }

  //  Assert the artifact actually landed: Bun.build silently drops output when given
  //  an unrecognised option, and result.success alone does not reveal that.
  const artifact = path.join(OUT_DIR, 'main.js');
  if (!existsSync(artifact)) {
    throw new Error(
      `JS 构建报告成功但产物未落盘 / build reported success but wrote nothing: ${artifact}\n` +
        `outputs=${JSON.stringify(result.outputs.map((o) => o.path))}`,
    );
  }
  console.log(`[build] main.js      ${((result.outputs[0]?.size ?? 0) / 1024).toFixed(1)} KB`);
}

/**
 * Build the CSS bundle.
 *
 * Deliberately NOT using bun's CSS bundler: it rewrites values, injects
 * absolute build-machine paths, and the stylesheet already contains an
 * unbalanced brace the parser may reject or "fix". Byte concatenation avoids all three.
 */
async function buildCss(): Promise<void> {
  const baseChunks: Uint8Array[] = [];
  const extraChunks: Uint8Array[] = [];

  for (const name of CSS_MODULES) {
    const file = path.join(ROOT, 'styles', name);
    if (!existsSync(file)) throw new Error(`缺少样式模块 / Missing style module: ${file}`);
    const bytes = new Uint8Array(await Bun.file(file).arrayBuffer());
    if ((CSS_MODULES_BASE as readonly string[]).includes(name)) baseChunks.push(bytes);
    else extraChunks.push(bytes);
  }

  const concat = (chunks: Uint8Array[]): Uint8Array => {
    const total = chunks.reduce((n, c) => n + c.length, 0);
    const out = new Uint8Array(total);
    let offset = 0;
    for (const chunk of chunks) {
      out.set(chunk, offset);
      offset += chunk.length;
    }
    return out;
  };

  //  The gate covers the original 13 modules only, so new styles cannot mask edits to them
  const baseDigest = md5(concat(baseChunks));
  if (baseDigest !== CSS_REFERENCE_MD5) {
    console.error(
      `[build] ✗ 既有样式模块与拆分前不一致 / base style modules differ from pre-split original:\n` +
        `        期望 expected ${CSS_REFERENCE_MD5}\n` +
        `        实际 actual   ${baseDigest}`,
    );
    throw new Error('样式等价性守门失败 / Style equivalence gate failed');
  }

  const merged = concat([...baseChunks, ...extraChunks]);
  await Bun.write(path.join(OUT_DIR, 'styles.css'), merged);
  console.log(
    `[build] styles.css   ${(merged.length / 1024).toFixed(1)} KB  ` +
      `(既有 md5 ${baseDigest.slice(0, 8)} ✓ 未改动; 新增模块 ${extraChunks.length} 个)`,
  );
}

/**
 * Copy the wasm artifact.
 *
 * Unlike main.js, the wasm is not bundled: it is copied verbatim and its size asserted
 * against the source, since a truncated copy is the classic failure here and would only
 * surface at runtime.
 */
async function buildWasm(): Promise<void> {
  if (!existsSync(SQL_WASM_SOURCE)) {
    throw new Error(
      `缺少 sql.js wasm / Missing sql.js wasm: ${SQL_WASM_SOURCE}\n` +
        `        请先运行 bun add sql.js / run "bun add sql.js" first`,
    );
  }

  const source = Bun.file(SQL_WASM_SOURCE);
  const target = path.join(OUT_DIR, SQL_WASM_NAME);
  await Bun.write(target, source);

  const expected = source.size;
  const actual = Bun.file(target).size;
  if (actual !== expected) {
    throw new Error(
      `wasm 复制不完整 / wasm copy truncated: ${actual} != ${expected} bytes`,
    );
  }
  console.log(`[build] ${SQL_WASM_NAME}   ${(actual / 1024).toFixed(1)} KB`);
}

/** Deploy into the vault plugin directory. */
async function deploy(): Promise<void> {
  if (!VAULT_PLUGIN_DIR) {
    throw new Error(
      'RTT_VAULT_PLUGIN_DIR is not set, so there is no deploy target.\n' +
        '        Example: RTT_VAULT_PLUGIN_DIR=/path/to/vault/.obsidian/plugins/documents-activity-tracker bun build.ts --deploy',
    );
  }

  for (const name of ['main.js', 'styles.css', SQL_WASM_NAME]) {
    const from = path.join(OUT_DIR, name);
    const to = path.join(VAULT_PLUGIN_DIR, name);
    if (!existsSync(from)) throw new Error(`产物不存在 / Missing artifact: ${from}`);
    await Bun.write(to, Bun.file(from));
    console.log(`[deploy] ${name} -> ${to}`);
  }
  console.log('[deploy] 完成。请在 Obsidian 中重新启用插件以加载新版本。');
  console.log('[deploy] Done. Re-enable the plugin in Obsidian to load the new build.');
}

/** Run one full build pass. */
async function run(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  await buildJs();
  await buildCss();
  await buildWasm();
  if (DEPLOY) await deploy();
  else console.log(`[build] -> ${OUT_DIR}`);
}

try {
  await run();
} catch (error) {
  console.error('[build] 构建失败 / Build failed:', error);
  if (!WATCH) process.exit(1);
}

if (WATCH) {
  console.log('[watch] 监听 src/ 与 styles/ ... / watching src/ and styles/ ...');
  for (const dir of ['src', 'styles']) {
    const watcher = watch(path.join(ROOT, dir), { recursive: true });
    void (async () => {
      for await (const _event of watcher) {
        try {
          await run();
        } catch (error) {
          console.error('[watch] 重建失败 / Rebuild failed:', error);
        }
      }
    })();
  }
}
