/**
 * build.ts — 构建脚本 / Build script
 *
 * 用法 / Usage:
 *   bun build.ts              # 开发构建 -> dist/（不压缩，带 inline sourcemap）
 *   bun build.ts --prod       # 生产构建 -> dist/（压缩）
 *   bun build.ts --deploy     # 生产构建并直接部署到 vault 插件目录
 *   bun build.ts --watch      # 监听 src/ 与 styles/ 增量重建
 *
 * 也可用环境变量覆盖产物目录 / Override output dir via env:
 *   RTT_OUT_DIR=/path/to/plugin bun build.ts
 *
 * 产物形状（Obsidian 的硬要求）/ Output shape (hard requirements from Obsidian):
 *   - 单文件 CommonJS `main.js`，只 require('obsidian')
 *   - 单文件 `styles.css`
 *
 * 本脚本不参与类型检查（tsconfig 刻意 exclude 它，以免引入 @types/node 依赖）。
 * This script is type-checked separately; tsconfig excludes it on purpose.
 */

import { mkdir, watch } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';

const ROOT = import.meta.dir;

/** vault 插件目录 —— 部署目标 / The vault plugin directory (deploy target). */
const VAULT_PLUGIN_DIR =
  '/home/corevortex/文档/Markdown Docs/.obsidian/plugins/documents-activity-tracker';

const OUT_DIR = process.env.RTT_OUT_DIR ?? path.join(ROOT, 'dist');

const PROD = process.argv.includes('--prod') || process.argv.includes('--deploy');
const DEPLOY = process.argv.includes('--deploy');
const WATCH = process.argv.includes('--watch');

const BANNER = '/* Documents Activity Tracker — generated by bun build. DO NOT EDIT. */';

/**
 * CSS 模块拼接顺序 —— 不可调换 / CSS concatenation order — MUST NOT be reordered.
 *
 * `60-widget-mobile` 及其后三块是 `10-widget` 桌面基础样式的覆盖层，
 * 选择器特异度相同，靠文档顺序取胜。顺序错了移动端布局会整体回退到桌面样式。
 *
 * Blocks from `60-widget-mobile` onward override the desktop base styles in
 * `10-widget`. Specificity is identical, so document order decides; a wrong
 * order makes the mobile layout fall back to desktop styling.
 */
const CSS_MODULES = [
  '00-header.css',
  '10-widget.css',
  '20-modal.css',
  '30-records-list.css',
  '40-timeline-view.css',
  '50-heatmap.css',
  '60-widget-mobile.css',
  '70-mobile-controls.css',
  '80-widget-collapse.css',
  '85-mobile-toggle.css',
  '90-session-detail.css',
  '92-state-sequence.css',
  '94-state-chain.css',
] as const;

/**
 * 样式等价性守门值 / Style equivalence gate.
 *
 * 这是拆分前单体 styles.css 的 md5。拼接是逐字节的，因此首次构建的产物
 * 必须仍然等于它 —— 一旦不等，说明样式被改动了（本次重构不允许）。
 *
 * md5 of the monolithic styles.css before the split. Concatenation is
 * byte-for-byte, so the output must still match it; any mismatch means styles
 * changed, which this refactor forbids.
 */
const CSS_REFERENCE_MD5 = 'd15dfb090e8fb907527dba913edf353c';

const md5 = (data: Uint8Array | string): string =>
  createHash('md5').update(data).digest('hex');

/** 构建 JS 产物 / Build the JS bundle. */
async function buildJs(): Promise<void> {
  const result = await Bun.build({
    entrypoints: [path.join(ROOT, 'src/main.ts')],
    // 注意：Bun.build 的 JS API 没有 `outfile`（那是 CLI 参数）。用 outdir + naming。
    // Note: the Bun.build JS API has no `outfile` (that's a CLI flag). Use outdir + naming.
    outdir: OUT_DIR,
    naming: 'main.js',
    format: 'cjs', // Obsidian 只加载 CommonJS / Loader requires CommonJS
    target: 'browser', // Electron 渲染进程，不是 node / Renderer process, not node
    external: ['obsidian'], // 由宿主注入，绝不打包 / Injected by the host, never bundled
    bundle: true,
    splitting: false, // 禁止多 chunk，Obsidian 只 require 单个 main.js
    minify: PROD,
    sourcemap: PROD ? 'none' : 'inline',
    banner: BANNER,
    define: {
      'process.env.NODE_ENV': JSON.stringify(PROD ? 'production' : 'development'),
    },
  });

  if (!result.success) {
    for (const log of result.logs) console.error('[build] ', log);
    throw new Error('JS 构建失败 / JS build failed');
  }

  // 断言产物确实落盘。Bun.build 会在遇到不认识的选项时静默丢弃输出，
  // 仅凭 result.success 无法发现，必须核实文件存在。
  // Assert the artifact actually landed: Bun.build silently drops output when given
  // an unrecognised option, and result.success alone does not reveal that.
  const artifact = path.join(OUT_DIR, 'main.js');
  if (!existsSync(artifact)) {
    throw new Error(
      `JS 构建报告成功但产物未落盘 / build reported success but wrote nothing: ${artifact}\n` +
        `outputs=${JSON.stringify(result.outputs.map((o) => o.path))}`,
    );
  }
  console.log(`[build] main.js      ${((result.outputs[0]?.size ?? 0) / 1024).toFixed(1)} KB`);
}

/**
 * 构建 CSS 产物 / Build the CSS bundle.
 *
 * 刻意【不】使用 bun 的 CSS 打包器：它会做值级改写（color: blue -> #00f）、
 * 插入构建机绝对路径注释，而 styles.css 本就存在一处括号不平衡（见
 * docs/ROLLBACK.md 第四节），解析器可能报错或"修复"它。
 * 逐字节拼接规避全部三个问题。
 *
 * Deliberately NOT using bun's CSS bundler: it rewrites values, injects
 * absolute build-machine paths, and the stylesheet already contains an
 * unbalanced brace the parser may reject or "fix". Byte concatenation avoids all three.
 */
async function buildCss(): Promise<void> {
  const chunks: Uint8Array[] = [];

  for (const name of CSS_MODULES) {
    const file = path.join(ROOT, 'styles', name);
    if (!existsSync(file)) throw new Error(`缺少样式模块 / Missing style module: ${file}`);
    chunks.push(new Uint8Array(await Bun.file(file).arrayBuffer()));
  }

  const total = chunks.reduce((n, c) => n + c.length, 0);
  const merged = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    merged.set(chunk, offset);
    offset += chunk.length;
  }

  const digest = md5(merged);
  if (digest !== CSS_REFERENCE_MD5) {
    console.error(
      `[build] ✗ styles.css 与拆分前不一致 / differs from pre-split original:\n` +
        `        期望 expected ${CSS_REFERENCE_MD5}\n` +
        `        实际 actual   ${digest}`,
    );
    throw new Error('样式等价性守门失败 / Style equivalence gate failed');
  }

  await Bun.write(path.join(OUT_DIR, 'styles.css'), merged);
  console.log(
    `[build] styles.css   ${(total / 1024).toFixed(1)} KB  (md5 ${digest.slice(0, 8)} ✓ 与拆分前一致)`,
  );
}

/** 部署到 vault 插件目录 / Deploy into the vault plugin directory. */
async function deploy(): Promise<void> {
  for (const name of ['main.js', 'styles.css']) {
    const from = path.join(OUT_DIR, name);
    const to = path.join(VAULT_PLUGIN_DIR, name);
    if (!existsSync(from)) throw new Error(`产物不存在 / Missing artifact: ${from}`);
    await Bun.write(to, Bun.file(from));
    console.log(`[deploy] ${name} -> ${to}`);
  }
  console.log('[deploy] 完成。请在 Obsidian 中重新启用插件以加载新版本。');
  console.log('[deploy] Done. Re-enable the plugin in Obsidian to load the new build.');
}

/** 执行一次完整构建 / Run one full build pass. */
async function run(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  await buildJs();
  await buildCss();
  if (DEPLOY) await deploy();
  else console.log(`[build] -> ${OUT_DIR}`);
}

try {
  await run();
} catch (error) {
  console.error('[build] 构建失败 / Build failed:', error);
  if (!WATCH) process.exit(1);
}

if (WATCH) {
  console.log('[watch] 监听 src/ 与 styles/ ... / watching src/ and styles/ ...');
  for (const dir of ['src', 'styles']) {
    const watcher = watch(path.join(ROOT, dir), { recursive: true });
    void (async () => {
      for await (const _event of watcher) {
        try {
          await run();
        } catch (error) {
          console.error('[watch] 重建失败 / Rebuild failed:', error);
        }
      }
    })();
  }
}
